<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>emojic</string>
	</array>
	<key>firstLineMatch</key>
	<string>-\*- Emojicode -\*-</string>
	<key>name</key>
	<string>Emojicode</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#classes</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.emojicode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.package-name.emojicode</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.module.emojicode</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(📦)\s*([^\s]+)\s*([^\s])</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(🏁)\s*(?:➡️\s*([^\s]))?\s*🍇</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.main.emojicode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.method.emojicode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>🍉</string>
			<key>name</key>
			<string>meta.function.main.emojicode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtin-types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control-flow</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>🍊|🍋|🍓|🔁|🔂|🍎</string>
			<key>name</key>
			<string>keyword.control.emojicode</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>builtin-types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>🍬?([🍨🍯]\s*🐚)?\s*(🚂|🚀|👌|🔣|🔡|⏩|✨)</string>
					<key>name</key>
					<string>support.type.s.emojicode</string>
				</dict>
			</array>
		</dict>
		<key>classes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(🐇\s*([^🐖\s])\s*([^🐖\s]?))[^🐖\s]*🍇</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.toc-list.class.emojicode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.emojicode</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.class.emojicode</string>
						</dict>
					</dict>
					<key>end</key>
					<string>🍉</string>
					<key>name</key>
					<string>meta.class.emojicode</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#declarative-statements</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#method-definitions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#initializer-definitions</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*👴{2,}\s+([^\s].*)$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.toc-list.emojicode</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*👴{3,}\s*$</string>
					<key>name</key>
					<string>meta.separator.emojicode</string>
					<key>while</key>
					<string>(?=im)possible</string>
				</dict>
				<dict>
					<key>match</key>
					<string>👴.*$</string>
					<key>name</key>
					<string>comment.line.older-man.emojicode</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>👵</string>
					<key>end</key>
					<string>👵</string>
					<key>name</key>
					<string>comment.block.older-woman.emojicode</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>🌮</string>
					<key>end</key>
					<string>🌮</string>
					<key>name</key>
					<string>comment.block.documentation.taco.emojicode</string>
				</dict>
			</array>
		</dict>
		<key>control-flow</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(🍊)\s*([^\s].*)\s*🍇</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.if.emojicode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#functional-statements</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>end</key>
					<string>🍉</string>
					<key>name</key>
					<string>meta.block.control.if.emojicode</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#functional-statements</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(🍋)\s*([^\s].*)\s*🍇</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.elseif.emojicode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#functional-statements</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>end</key>
					<string>🍉</string>
					<key>name</key>
					<string>meta.block.control.elseif.emojicode</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#functional-statements</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(🍓)\s*🍇</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.else.emojicode</string>
						</dict>
					</dict>
					<key>end</key>
					<string>🍉</string>
					<key>name</key>
					<string>meta.block.control.else.emojicode</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#functional-statements</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(🔁)\s*([^\s].*)\s*🍇</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.while.emojicode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#functional-statements</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>end</key>
					<string>🍉</string>
					<key>name</key>
					<string>meta.block.control.while.emojicode</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#functional-statements</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(🔂)\s*(\b[^\s]+\b)\s*(?:(\b[^\s]+\b)|([^\s].*))\s*🍇</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.for.emojicode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.loop.emojicode</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.loop.emojicode</string>
						</dict>
						<key>4</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#functional-statements</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>end</key>
					<string>🍉</string>
					<key>name</key>
					<string>meta.block.control.for.emojicode</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#functional-statements</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.return.emojicode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.emojicode</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#functional-statements</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>match</key>
					<string>(🍎)\s*(?:(\b[^\s]+\b)|([^\s].*))</string>
				</dict>
			</array>
		</dict>
		<key>declarative-statements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-declarations</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtin-types</string>
				</dict>
			</array>
		</dict>
		<key>functional-statements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtin-types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control-flow</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method-calls</string>
				</dict>
			</array>
		</dict>
		<key>initializer-definitions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>[\s🐇🖋🔏🔓🔐🔒]*🐈\s*([^\s]).*🍇</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.initializer.emojicode</string>
						</dict>
					</dict>
					<key>end</key>
					<string>🍉</string>
					<key>name</key>
					<string>meta.function.initializer.emojicode</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#functional-statements</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b\d[\d_]*?(\.\d+)?\b</string>
					<key>name</key>
					<string>constant.numeric.decimal.emojicode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b0x\h+\b</string>
					<key>name</key>
					<string>constant.numeric.hexadecimal.emojicode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>🔟.</string>
					<key>name</key>
					<string>constant.character.emojicode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>👍</string>
					<key>name</key>
					<string>constant.language.true.emojicode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>👎</string>
					<key>name</key>
					<string>constant.language.false.emojicode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>⚡️</string>
					<key>name</key>
					<string>constant.language.nothingness.emojicode</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>🔤</string>
					<key>end</key>
					<string>((?&lt;!❌)|(?&lt;=❌❌))🔤</string>
					<key>name</key>
					<string>string.other.emojicode</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>❌[❌🔤ntre]</string>
							<key>name</key>
							<string>constant.character.escape.emojicode</string>
						</dict>
						<dict>
							<key>match</key>
							<string>❌.</string>
							<key>name</key>
							<string>invalid.illegal.unknown-escape.emojicode</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>method-calls</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.method.emojicode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.emojicode</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#functional-statements</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>match</key>
					<string>([^\s\w])\s*(?:(\b[^\s]+\b)|([^\s].*))</string>
					<key>name</key>
					<string>meta.function-call.method.emojicode</string>
				</dict>
			</array>
		</dict>
		<key>method-definitions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*[\s🐇🖋🔏🔓🔐🔒]*🐖\s*([^\s])(.*?)(?:➡️\s*([^\s]))?\s*🍇</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.method.emojicode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#builtin-types</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#builtin-types</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>end</key>
					<string>🍉</string>
					<key>name</key>
					<string>meta.function.method.emojicode</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#functional-statements</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.method.native.emojicode</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.emojicode</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*[\s🐇🖋🔏🔓🔐🔒]*🐖\s*([^\s]).*?(?:➡️\s*[^\s])?\s*📻</string>
					<key>name</key>
					<string>meta.function.method.native.emojicode</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>😜|◀️|▶️|⬅️|➡️|➕|➖|✖️|➗|🚮|🎊|🎉|❎|⭕️|💢|❌|🚫|👈|👉</string>
					<key>name</key>
					<string>keyword.operator.emojicode</string>
				</dict>
			</array>
		</dict>
		<key>variable-declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.variable-declare.emojicode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.toc-list.variable.emojicode</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.class.emojicode</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(🍰)\s*(([^\s]+)\s*(🍬\s*.|[🍨🍯]\s*🐚\s*.|.))</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.variable-declare.emojicode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.emojicode</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(🍰)\s*([^\s]+)\s*?(?=[^\s])</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.variable-assign.emojicode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.emojicode</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(🍮)\s*((\w)+)\s*?(?=[^\s])</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.variable-freeze.emojicode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.emojicode</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(🍦)\s*((\w)+)\s*?(?=[^\s])</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.emojicode</string>
	<key>uuid</key>
	<string>2CE9D351-3AB0-4D6D-A1B5-24D2024B3430</string>
</dict>
</plist>
